// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRSuPdXPawrvhEC8SPxNPqo1AMbxHSWag',
    appId: '1:1066305914426:web:15b20f40480630033ed703',
    messagingSenderId: '1066305914426',
    projectId: 'depi-shecoders-team-233d1',
    authDomain: 'depi-shecoders-team-233d1.firebaseapp.com',
    storageBucket: 'depi-shecoders-team-233d1.appspot.com',
    measurementId: 'G-FEY6WXM4T8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6p39ofk8WWk0JRGV2o86Y0V_ovj-Wveo',
    appId: '1:1066305914426:android:cf20b1148fb7f5973ed703',
    messagingSenderId: '1066305914426',
    projectId: 'depi-shecoders-team-233d1',
    storageBucket: 'depi-shecoders-team-233d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUv64BVI6zkwZUZQdgAfRjh6ssCXOjcq4',
    appId: '1:1066305914426:ios:92e18f0ee1f967643ed703',
    messagingSenderId: '1066305914426',
    projectId: 'depi-shecoders-team-233d1',
    storageBucket: 'depi-shecoders-team-233d1.appspot.com',
    androidClientId: '1066305914426-nek4qmin5or9fl6ggr3rr6lb8d1cqcu0.apps.googleusercontent.com',
    iosClientId: '1066305914426-a838h97c7tnpl5sglik422c5m990k5va.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUv64BVI6zkwZUZQdgAfRjh6ssCXOjcq4',
    appId: '1:1066305914426:ios:92e18f0ee1f967643ed703',
    messagingSenderId: '1066305914426',
    projectId: 'depi-shecoders-team-233d1',
    storageBucket: 'depi-shecoders-team-233d1.appspot.com',
    androidClientId: '1066305914426-nek4qmin5or9fl6ggr3rr6lb8d1cqcu0.apps.googleusercontent.com',
    iosClientId: '1066305914426-a838h97c7tnpl5sglik422c5m990k5va.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRSuPdXPawrvhEC8SPxNPqo1AMbxHSWag',
    appId: '1:1066305914426:web:7601519b935280a03ed703',
    messagingSenderId: '1066305914426',
    projectId: 'depi-shecoders-team-233d1',
    authDomain: 'depi-shecoders-team-233d1.firebaseapp.com',
    storageBucket: 'depi-shecoders-team-233d1.appspot.com',
    measurementId: 'G-YEHD2Z58QQ',
  );
}
